### ISSUE TITLE
off-topic, concerning an issue on SO

### ISSUE THREAD

**Issue by BitProcessor** [sergionsk8/katacoda-scenarios#1]
Hi! 

Sorry to contact you this way, but I'm hoping you are the person behind: 
https://stackoverflow.com/questions/63674729/python-http-get-raise-exception-after-300-seconds-from-docker-container

If so, I'm having the exact same issue with a long running connection + Docker (and curl inside docker works fine) and I was wondering if you ever figured out a solution. I'm running into the problem with a Java application, but the symptoms are exactly the same on network level.

I've been wiresharking to see what Curl does different, but slowly losing my mind ;-) 

Would appreciate it a lot if you could get back to me.

Thanks in advance,
Maarten

**Comment by BitProcessor** [comment]
Fixed

**Comment by sergionsk8** [comment]
Hi,
I'm sorry I didn't see your message before. I didn't solve the issue but I used a workaround, can you share your solution directly on stackoverflow?

Thank you,
Sergio
